# version:'3'
# services:
#   nginx:
#    image:nginx
#    container_name:webpack-vue-demo
#    build:.
#    ports:
#     - 3000:80
#     volumes:
#      -  ~/DockerCompose/webpack-vue-demo/dist:/usr/share/nginx/html
#      - ~/DockerCompose/webpack-vue-demo/nginx.conf:/etc/nginx/nginx.conf
#    privileged:true
version: '3'
services:
  nginx:
    image: nginx
    container_name: webpack-vue-demo
    build: .
    ports:
      - '8080:80'
    volumes:
      - '~/DockerCompose/webpack-vue-demo/dist:/usr/share/nginx/html'
      - '~/DockerCompose/webpack-vue-demo/nginx.conf:/etc/nginx/nginx.conf'
    privileged: true
